import 'package:flutter/painting.dart';

/// A 2D point in normalized [0..1] coordinate space, generated by a dynamical
/// system. The renderer maps these to canvas coordinates.
class WallpaperPoint {
  const WallpaperPoint(this.x, this.y, [this.intensity = 1.0]);

  final double x;
  final double y;

  /// 0..1, derived from trajectory density. Used for alpha modulation.
  final double intensity;

  Offset get offset => Offset(x, y);
}
